export const Routes = {
  NOTIFICATION: '/notification',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  OTP: '/otp',
  GOOGLE_CALLBACK: '/google-callback',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  PROFILE: '/profile',
  TEMPLATES: '/templates',
  SCREENS: '/screens',
  ANALYTICS: '/analytics',
  COLLABORATION: '/collaboration',
  PLAYLISTS: '/playlists',
  ADMIN_COMPANIES: '/admin/companies',
  ADMIN_REQUESTS: '/admin/requests',
  PLAYER: '/player/:screenId',
  RECYCLE_BIN: '/recycle-bin',
  ERROR: {
    GENERAL: '/500',
    NOT_FOUND: '/404',
    MAINTENANCE: '/503',
  },
  FALLBACK: '*',
}
